base/urls.py
from django.urls import path
from .import views

urlpatterns=[
    path('',views.home,name='home'),
    path('candidate/',views.candidate,name='candidate'),
    path('can-register/',views.candidate_register,name='candidate-register'),
    path('voter-register/',views.voter_register,name='voter-register'),
    path('voter-list/',views.voter_list,name='voter-list'),
    path('voter-details/<str:pk>/',views.voter_details,name='voter-details'),
    path('vote-update/<str:pk>/',views.update_voter,name='vote-update'),
    path('candidate-profile/<str:pk>/',views.candidate_profile,name='candidate-profile'),
    path('candidate-update/<str:pk>/',views.update_candidate,name='candidate-update'),
    path('position/',views.position,name='position'),
    path('position-details/<str:pk>/',views.position_candidate,name='position-details'),
    path('result/',views.results,name='result'),
]

polls/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
    path('gateway/',include('gateway.urls')),
    path('gateway/',include('django.contrib.auth.urls')),
]

base/models.py
from django.db import models
from django.contrib.auth.models import User


class Position(models.Model):
    title = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.title


class Candidate(models.Model):
    username=models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    first_name=models.CharField('First Name',max_length=100)
    last_name=models.CharField('Last Name',max_length=100)
    position = models.ForeignKey(Position, on_delete=models.CASCADE,null=True)
    college_name=models.CharField('College Name',max_length=50)
    total_vote = models.IntegerField(default=0, editable=False,null=True)
    student_id=models.CharField('Student id',max_length=50)
    phone_number=models.CharField('Phone Number',max_length=50)
    e_mail=models.EmailField('E-Mail', max_length=50,blank=True)
    adhaar_card_no=models.CharField('Adhaar Card Number',max_length=50)
    created=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.first_name + " " + self.last_name



class Voters(models.Model):
    username =  models.ForeignKey(User, on_delete=models.SET_NULL,null=True)
    first_name=models.CharField('First Name',max_length=100)
    last_name=models.CharField('Last Name',max_length=100)
    student_id=models.CharField('Student id',max_length=50)
    adhaar_card_no=models.CharField('Adhaar Card Number',max_length=50)

    def __str__(self):
        return self.first_name + " " + self.last_name

class ControlVote(models.Model):
    voter = models.ForeignKey(User, on_delete=models.CASCADE)
    position = models.ForeignKey(Position, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)

    def __str__(self):
        return "{} - {} - {}".format(self.voter, self.position, self.status)

base/forms.py
from .models import *
from django.forms import ModelForm

class CandidateForm(ModelForm):
    class Meta:
        model=Candidate
        fields='__all__'
        exclude=['total_vote']

class VotersForm(ModelForm):
    class Meta:
        model=Voters
        fields='__all__'

base/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .forms import CandidateForm,VotersForm
from django.contrib.auth.decorators import login_required
from .models import *
from django.contrib import messages



def home(request):
    return render(request,'base/home.html')


@login_required(login_url='login')
def candidate_register(request):
    submitted=False
    if request.method=='POST':
        form=CandidateForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/can-register?submitted=True')
    else:
        form=CandidateForm()
        if 'submitted' in request.GET:
            submitted=True

    context={'form':form,'submitted':submitted}
    return render(request,'base/candidate_register.html',context)


@login_required(login_url='login')
def candidate(request):
    candidates=Candidate.objects.all()
    context={'candidates':candidates}
    return render(request,'base/candidate.html',context)


@login_required(login_url='login')
def candidate_profile(request,pk):
    profile=Candidate.objects.get(id=pk)
    context={'profile':profile}
    return render (request,'base/candidate_profile.html',context)


@login_required(login_url='login')
def update_candidate(request,pk):
    candidate=Candidate.objects.get(id=pk)
    form=CandidateForm(request.POST or None,instance=candidate)
    if form.is_valid():
        form.save
        return redirect('/candidate')

    context={'form':form,'candidate':candidate}
    return render(request,'base/candidate_update.html',context)


@login_required(login_url='login')
def voter_register(request):
    submitted=False
    if request.method=='POST':
        form=VotersForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/voter-register?submitted=True')
    else:
        form=VotersForm()
        if 'submitted' in request.GET:
            submitted=True

    context={'form':form,'submitted':submitted}
    return render(request,'base/voter_register.html',context)



@login_required(login_url='login')
def voter_list(request):
    voters=Voters.objects.all()
    context={'voters':voters}
    return render(request,'base/voter_list.html',context)



def voter_details(request,pk):
    details=Voters.objects.get(id=pk)
    context={'details':details}
    return render(request,'base/voter_details.html',context)



@login_required(login_url='login')
def update_voter(request,pk):
    voter=Voters.objects.get(id=pk)
    form=VotersForm(request.POST or None,instance=voter)
    if form.is_valid():
        form.save()
        messages.success(request,"Successfully updated")
        return redirect('/voter-list')

    context={'form':form,'voter':voter}
    return render(request,'base/voter_update.html',context)


@login_required(login_url='login')
def position(request):
    pos=Position.objects.all()
    context={'pos':pos}
    return render(request,'base/position.html',context)


@login_required(login_url='login')
def position_candidate(request, pk):
    obj = get_object_or_404(Position, id=pk)
    profile=Candidate.objects.all()

    if request.method == "POST":
        temp = ControlVote.objects.get_or_create(voter=request.user, position=obj)[0]
        if temp.status == False:
            temp2 = Candidate.objects.get(id=request.POST.get(obj.title))
            temp2.total_vote += 1
            temp2.save()
            temp.status = True
            temp.save()
            return redirect('/position/')
        else:
            messages.success(request, 'You Have Already Been Voted For This Position.')
            return render(request, 'base/position_details.html', {'obj':obj,'profile':profile})
    else:
        return render(request, 'base/position_details.html', {'obj':obj,'profile':profile})


@login_required(login_url='login')
def results(request):
    results = Candidate.objects.all().order_by('position','-total_vote')
    context={'results':results}
    return render(request,'base/result.html',context)

base/templates/base/candidate.html
{% extends 'base/main.html' %}

{% block content %}

<div>
    <h1>List of Candidates</h1>
</div>

<div>
    {{user}}---{{user.id}}
    <br/><br/>
    {% if user.is_authenticated %}
        {% for candidate in candidates %}
            {% if request.user == candidate.username %}
                <a href="{% url 'candidate-profile' candidate.id %}">{{candidate.id}}--{{candidate}}</a>
                <a href="{% url 'candidate-update' candidate.id %}"><span>Update</span></a>
                <br/><br/>
            {% else %}
                <a href="{% url 'candidate-profile' candidate.id %}">{{candidate.id}}--{{candidate}}</a>
                <br/><br/>
            {% endif %}
        {% endfor %}        
    {% endif %}
</div>

{% endblock content %}

base/templates/base/candidate_profile.html
{% extends 'base/main.html' %}

{% block content %}

<center>

    {% if request.user == profile.username %}
        <h1>My Profile</h1>
        {{profile}}<br/>
        {{profile.college_name}}<br/>
        {{profile.student_id}}<br/>
        {{profile.e_mail}}<br/>
        {{profile.phone_number}}<br/>
        {{profile.adhaar_card_no}}<br/>
        {{profile.created}}<br/>
        <br/>
        <br/>
    {% else %}
        <h1>Access Denied</h1>
    {% endif %}

</center>

{% endblock content %}

base/templates/base/candidate_register.html
{% extends 'base/main.html' %}

{% block content %}
<div>
    <center>
        <h1>Candidate Registration</h1>
        <br/><br/>
        {% if user.is_authenticated %}
            {% if submitted %}
                <p>You are Sucessfully Registered</p>
                <a href="{% url 'home' %}"><Button>Home Pg</Button></a>
            {% else %}
                <form action="" method="POST">
                    {% csrf_token %}
                    {{form.as_p}}
                    <input type="submit" value="submit"/>
                </form>
            {% endif %}
        {% else %}
            <h3>Access Denied</h3>
            <p>First Sign up/Login Than Register!</p>
            <a href="{% url 'register' %}"><button>Sign up</button></a>
        {% endif %}
    </center>
</div>
{% endblock content %}

base/templates/base/candidate_update.html
{% extends 'base/main.html' %}

{% block content %}
<div>
    <h1>Update My Profile</h1>
</div>

<div>
    <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Update"/>
    </form>
</div>

{% endblock content %}

base/templates/base/home.html
{% extends 'base/main.html' %}

{% block content %}

<div>
    <div>
        {% if messages %}

            {% for message in messages %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>{{message}}&nbsp</strong>&nbspThank You For Visiting.
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}

        {% endif %}
    </div>
</div>

<div>
    <div>
        <h1>Welcome to Online Voting System</h1>
        <h3>Check the links above</h3>
        
    </div>
</div>

{% endblock content %}

base/templates/base/main.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet">
    <title>College Election</title>
</head>

<body>
    <div>
        <nav class="navbar navbar-dark bg-dark">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'home' %}">College Election</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Dashboard
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">

                      <li><a class="dropdown-item" href="{% url 'candidate'  %}">View Candidate</a></li>
                      <li><a class="dropdown-item" href="{% url 'candidate-register' %}">Sign up As Candidate</a></li>
                      <li><a class="dropdown-item" href="{% url 'voter-list' %}">View Voters</a></li>
                      <li><a class="dropdown-item" href="{% url 'voter-register' %}">Sign up As Voter</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="{% url 'position' %}">Position</a></li>
                      <li><a class="dropdown-item" href="{% url 'result' %}">Results</a></li>

                    </ul>
                  </li>
                  {% if user.is_authenticated %}
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                  {% else %}
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'register' %}">Sign Up</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                  {% endif %}
                </ul>
                <form class="d-flex">
                  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
              </div>
            </div>
          </nav>
    </div>

    <div class="container">
      {% block content %}


      {% endblock %}
    </div>
   
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous">
    </script>
</body>
</html>

base/templates/base/position.html
{% extends 'base/main.html' %}

{% block content %}
<h2>Available Position For Vote</h2>
  <ul>
    {% for i in pos %}
      <li><a href="{% url 'position-details' i.id %}">{{i.title}}</a></li>
    {% empty %}
      <p>No Positions Available</p>
    {% endfor %}
  </ul>
{% endblock content %}

base/templates/base/position_details.html
{% extends 'base/main.html' %}

{% block content %}
<div>
    <div>
        <h2>Candidate Avaliable for Position of {{candidate.title}}</h2>
    </div>

    <div>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-danger" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    </div>

    <div>
        <form action="" method="POST">
            {% csrf_token %}
            {% for c in obj.candidate_set.all %}
            <div class="custom-control custom-radio">
                <input type="radio" id="id_{{c.id}}" name="{{ c.position}}" value="{{c.id}}"
                    class="custom-control-input" required>
                <label class="custom-control-label" for="id_{{c.id}}">{{c}} <a href="{% url 'candidate-profile' c.id %}">Detail</a></label>
            </div>
            {% empty %}
            <p>No Candidates Available</p>
            {% endfor %}
            <br><input type="submit" class="btn btn-outline-success btn-sm" value="VOTE">
        </form>
        <br>
        <p><a href="{% url 'position' %}">Back to Poll</a></p>
    </div>
</div>

{% endblock content %}

base/templates/base/result.html
{% extends 'base/main.html' %}

{% block content %}

<div>
    <h1>Election Results</h1>
    {% if request.user.is_superuser %}
        <h2 class="text-center">Result</h2>
        <table class="table table-bordered table-sm text-center">
            <thead>
                <tr>
                    <th>Candidate Name</th>
                    <th>Candidate Position</th>
                    <th>Total Vote</th>
                </tr>
            </thead>
            <tbody>
                {% for i in results %}
                <tr>
                    <td>{{ i.first_name }}&nbsp{{ i.last_name }}</td>
                    <td>{{ i.position }}</td>
                    <td>{{ i.total_vote }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
    <p>Access Denied</p>
    {% endif %}

</div>

{% endblock content %}

base/templates/base/voter_details.html
{% extends 'base/main.html' %}

{% block content %}
<div>
    <center>
        <h1>voter Details</h1>
        {{details}}<br/>

    </center>
</div>
{% endblock content %}

base/templates/base/voter_list.html
{% extends 'base/main.html' %}

{% block content %}

<div>

    <div>
        <h1>Voter List</h1>
        {{user}}----{{user.id}}
        <br/><br/>
        <center>
            {% if messages %}
                {% for message in messages %}
                    {{message}}
                {% endfor %}
            {% endif %}
        </center>
    </div>

    <div>

        {% for voter in voters %}
            <div>
                {% if user.is_authenticated %}
                    {% if request.user == voter.username %}
                        <a href="{% url 'voter-details' voter.id %}"><span>{{voter.id}}--{{voter}}</span></a>
                        <a href="{% url 'vote-update' voter.id %}">Update</a>
                        <a href="{% url 'position' %}"><button>Vote</button></a>
                        <br /><br />
                    {% else %}
                        <a href="{% url 'voter-details' voter.id %}"><span>{{voter.id}}--{{voter}}</span></a>
                    {% endif %}
                {% endif %}
            </div>
        {% endfor %}

    </div>

</div>

{% endblock content %}

base/templates/base/voter_register.html
{% extends 'base/main.html' %}

{% block content %}

<div>
    <center>
        <h1>Voters Registration</h1>
        <br/><br/>
        {% if submitted %}
            <p>You are Sucessfully Registered</p>
            <a href="{% url 'home' %}"><Button>Home Pg</Button></a>
        {% else %}
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <input type="submit" value="submit"/>
            </form>
        {% endif %}
    </center>
</div>

{% endblock content %}

base/templates/base/voter_update.html
{% extends 'base/main.html' %}

{% block content %}

<div>
    <h1>Edit Your Details</h1>
</div>
Logged in user--{{user}}
Voter:{{voter.username}}

<div>
    <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Update"/>
    </form>
</div>

{% endblock content %}